### ISSUE TITLE
l10n functions problems

### ISSUE THREAD

**Issue by NANASHI0X74** [amake/flutter.el#15]
hi, I'm having trouble with the `flutter-l10n-externalize-at-point` function.

The first thing I noticed is that apparently the flutter documentation now recommends a different approach to localisation which is to write these arb (json) files with the strings we want and let flutter generate the localisation classes from that. These are written to `$ROJECTROOT/.dart_tool/flutter_gen/gen_l10n/app_localizations.dart` so I changed the `flutter-l10n-file` variable.

But then I get another error:
`error: "Invalid search bound (wrong side of point)"`
With my as of yet rudimentary edebug skills I've observed that this gets thrown while in `flutter-l10n--delete-applied-consts` but I don't really understand why. This shouldn't be something that's affected by the `flutter-l10n-file`, or should it?

**Comment by amake** [comment]
> The first thing I noticed is that apparently the flutter documentation now recommends a different approach to localisation which is to write these arb (json) files with the strings we want and let flutter generate the localisation classes from that.

Yes, the flutter-l10n stuff is still assuming the old system, where you write Dart code and generate an ARB from that.



> so I changed the `flutter-l10n-file` variable.

To what?

> But then I get another error:

When? (I assume when executing `flutter-l10n-externalize-at-point`?)

> With my as of yet rudimentary edebug skills I've observed that this gets thrown while in `flutter-l10n--delete-applied-consts` but I don't really understand why.

I assume the "why" you're talking about is "why the error is thrown", but first "why `flutter-l10n--delete-applied-consts` is called":

Externalizing a string means taking a string literal and replacing it with a method call. A method call can't be `const`, so when extracting the string literal we remove any `const` tokens that might apply to that spot.

As for why `flutter-l10n--delete-applied-consts` is giving an error: I think I need to see the actual Dart code you're working on. Even better if you can boil it down to the minimum that allows reproducing the issue.

**Comment by NANASHI0X74** [comment]
> > so I changed the `flutter-l10n-file` variable.
> 
> To what?

to `.dart_tool/flutter_gen/gen_l10n/app_localizations.dart`

> > But then I get another error:
> 
> When? (I assume when executing `flutter-l10n-externalize-at-point`?)

yes exactly, I guess I forgot to clarify :sweat_smile:


> Externalizing a string means taking a string literal and replacing it with a method call. A method call can't be `const`, so when extracting the string literal we remove any `const` tokens that might apply to that spot.

yeah I understand why it's needed :)

> As for why `flutter-l10n--delete-applied-consts` is giving an error: I think I need to see the actual Dart code you're working on. Even better if you can boil it down to the minimum that allows reproducing the issue.

ok, I've copied the file I was working on and then went on to delete stuff until I couldn't reproduce the error.
Surprisingly this very simple code already produced the error:
```dart
class DashboardScreen extends StatelessWidget {
  String astring= 'stringtotranslate';
  @override
  Widget build(BuildContext context) {
    return Text('stringtotranslate');
  }
}
```
The first string doesn't cause any problems, but the second string (in the text widget) does.
Stepping through the debugger again, it seems to me like the positions that are returned from `(match-beginning 0)` -https://github.com/amake/flutter.el/blob/696228a619f6078b16f9f77071112f6ad2a25c4e/flutter-l10n.el#L211 are wrong. Could that possibly have something to do with my own emacs configuration/version/how it was compiled?

When I call the externalize function, this is what `(flutter-l10n--nesting-at-point)` evaluates to once it's encountered in both calls:
for the first string:
```elisp
Result: ((#("{" 0 1 (fontified t)) . 2))
```
for the second one:
```elisp
Result: ((#("(" 0 1 (fontified t)) . 0) (#("{" 0 1 (fontified t)) . 2) (#("{" 0 1 (fontified t)) . 2))
```

**Comment by amake** [comment]
> Stepping through the debugger again, it seems to me like the positions that are returned from `(match-beginning 0)` -
> https://github.com/amake/flutter.el/blob/696228a619f6078b16f9f77071112f6ad2a25c4e/flutter-l10n.el#L211
>  are wrong.

Good call. They are indeed wrong. When I check whether `char` is an open or close delimiter I use `string-match`, but this clobbers the regex match data that I store with `(match-beginning 0)`.

> Could that possibly have something to do with my own emacs configuration/version/how it was compiled?

It's probably the version: it accidentally worked on the version of Emacs I developed and used this on, but internal changes in Emacs probably exposed the bug afterwards.

I haven't been using `flutter-l10n` for quite a while, as I changed jobs.

Thanks for the report. The fix should be on MELPA soon.
