### ISSUE TITLE
Running in no-sound-null-safety

### ISSUE THREAD

**Issue by dchrzanowski** [amake/flutter.el#16]
Hello, thank you for your work on this package, it's just perfect for my current needs.
However, with the update to Flutter 2, some of the libs I use have not updated yet to null safety, so I have a temporary need to run flutter with `flutter run --no-sound-null-safety`. How would I go about adding the `--no-sound-null-safety` command line parameter?

**Comment by amake** [comment]
Right now there are three ways to do it:

1. Call `flutter-run` with a prefix argument: `C-u M-x flutter-run` and enter `--no-sound-null-safety` at the prompt
2. Define a wrapper function

    ```elisp
    (defun my-flutter-run ()
      (flutter-run "--no-sound-null-safety"))
    ```

    But this would require altering key bindings.
3. Advise the existing `flutter-run` function:

    ```elisp
    (defun my-flutter-run-advice (old-func &rest args)
      (apply old-func `("--no-sound-null-safety" ,@args)))
    (advice-add #'flutter-run :around #'my-flutter-run-advice)
    ```

    This has the advantage of working with all existing key bindings.

Note that I didn't test any of the above code.
