### ISSUE TITLE
How do I view the log output?

### ISSUE THREAD

**Issue by Cir0X** [amake/flutter.el#18]
Sorry if this is a stupid question but I can't find a buffer where I can view the [`log`](https://api.dart.dev/stable/2.12.2/dart-developer/log.html) or [`print`](https://api.dart.dev/stable/2.12.2/dart-core/print.html) output.  
I'm using `flutter-run-or-hot-reload` in order to run my app on an iOS simulator.

**Comment by amake** [comment]
Any log output available to Flutter will be in the `*Flutter*` buffer. If there's nothing there, then there wouldn't have been anything there even if you were running from the CLI without flutter.el. So I suggest you try running `flutter run` from your terminal and see if you get the same results.

Especially for iOS (and maybe even then, *especially* for the Simulator) I've found that as Flutter and iOS change over time, sometimes `flutter run` can output logs and sometimes it can't. When Flutter does not output logs, running from Xcode will allow you to see the logs.

If we are in an epoch where `flutter run` can't show Simulator logs, then there is really nothing I can do about it and I suggest you launch your app from Xcode instead.

**Comment by Cir0X** [comment]
The `*Flutter*` buffer just shows Errors, but the [DevTools](https://flutter.dev/docs/development/tools/devtools/overview) `Logging` tab shows all log messages.
Thank you for your help.
