### ISSUE TITLE
after save hook?

### ISSUE THREAD

**Issue by bbuccianti** [amake/flutter.el#2]
Hi!
I want to use flutter with emacs and really want to run the function flutter-run-or-hot-reload after I save a file of my flutter project. Any idea how do we implement this?

Thank you!

**Comment by amake** [comment]
You can add it to `after-save-hook`. If using `use-package`:

```lisp
(use-package dart-mode
  :hook (dart-mode . (lambda ()
                      (add-hook 'after-save-hook #'flutter-run-or-hot-reload nil t))))
```

**Comment by bbuccianti** [comment]
Thank you!!

**Comment by sedbytes** [comment]
> You can add it to `after-save-hook`. If using `use-package`:
> 
> ```lisp
> (use-package dart-mode
>   :hook (dart-mode . (lambda ()
>                       (add-hook 'after-save-hook #'flutter-run-or-hot-reload nil t))))
> ```

Thanks for this!

I believe this is quite a common expectation from a flutter plugin. Maybe consider adding this to the README?
