### ISSUE TITLE
RFI : can I launch an android emulator ? 

### ISSUE THREAD

**Issue by rileyrg** [amake/flutter.el#26]
when I flutter-run, I can run in chrome or as a Linux app. Is there some way to launch the app to emulator?

**Comment by amake** [comment]
I assume "emulator" is the Android emulator and your app is a mobile app. In that case you need to make sure the emulator is running before you execute `flutter-run`.

**Comment by rileyrg** [comment]
> I assume "emulator" is the Android emulator and your app is a mobile app. In that case you need to make sure the emulator is running before you execute `flutter-run`.

Yes, android. It's in the title. Thanks for the quick reply.

**Comment by amake** [comment]
Oops, sorry I missed the title.

Alternatively if you can figure out the CLI invocation for launching the emulator then you could define a function `flutter-launch-emulator-and-run`.

**Comment by rileyrg** [comment]
No worries. And thanks. Its prompting me for JAVA_HOME which is a surprise since ANDROID_HOME is set and flutter is on the command line and apk deployment runs fine from Android Studio.  I need to look into it. Is it just me or does JAVA/Android constantly change the env requirements. ;)

**Comment by rileyrg** [comment]
FYI I install openjdk 18 on Ubuntu 20.10, and it then worked, leaving me to ask how come AS worked without it. I assume because it has its own JDK somewhere. I need to see if I can locate that.  Thanks again, works fine - though I would prefer to be prompted which app to run - if the emulator is open it uses that rather than prompt chrome, linux or emulator.

**Comment by amake** [comment]
I think Android Studio does bundle its own Java runtime.

flutter.el simply invokes the `flutter` CLI tool, so however that behaves is what you should expect in flutter.el, including the behavior regarding which device is chosen.

**Comment by rileyrg** [comment]
Just for completeness, I removed my openjdk and added this to use my Android Studio  bundled jdk.

```
  (use-package flutter
    :after dart-mode
    :config
    (setenv "JAVA_HOME" (concat (getenv "ANDROID_STUDIO_HOME") "/jbr"))
    :bind (:map dart-mode-map
                ("C-M-x" . #'flutter-run-or-hot-reload)))

```

edit: used ANDROID_STUDIO_HOME

**Comment by confusedalex** [comment]
I've implemented a little utility function to start an emulator.

```elsip
 (defun flutter-launch-emulator (emulator-id)
  "Launches the emulator with the given ID."
  (interactive
   (list (completing-read "Emulator: " (flutter--emulators))))
  (shell-command (format "flutter emulators --launch %s" emulator-id))
  )

(defun flutter--emulators ()
  "Return an list of emulators."
  (string-lines (shell-command-to-string "emulator -list-avds") t)
  )
```

**Comment by amake** [comment]
Nice. I don't have `emulator` on my $PATH but for me it's at `$ANDROID_HOME/emulator/emulator`.

**Comment by confusedalex** [comment]
is this worth upstreaming?
