### ISSUE TITLE
Compile error during install, symbol’s value as variable is void: flutter-interactive-keys-alist

### ISSUE THREAD

**Issue by bradyt** [amake/flutter.el#3]
Not sure if this is mission critical, but just putting it here for your convenience.

When I do `M-x package-install RET flutter RET`, I see the following in `*Compile log*` buffer.

```
^L
Compiling internal form(s) at Wed Jun  5 17:44:17 2019
Leaving directory ‘/Users/alice/.emacs.d/elpa/flutter-20190204.601’
^L
Compiling file /Users/alice/.emacs.d/elpa/flutter-20190204.601/flutter.el at Wed Jun  5 17:44:17 2019
Entering directory ‘/Users/alice/.emacs.d/elpa/flutter-20190204.601/’
flutter.el:80:1:Error: Symbol’s value as variable is void: flutter-interactive-keys-alist
```

**Comment by amake** [comment]
I get this error from Flycheck as well when I open `flutter.el`. I would love to fix this, but I don't understand it. `flutter-interactive-keys-alist` is defined earlier in the file, and should exist when `flutter-register-keys` runs. And despite the error, it seems to work.

If someone could help me understand this, I would be very grateful.
