### ISSUE TITLE
[feature request] "Killing Gradle on exit"

### ISSUE THREAD

**Issue by stradicat** [amake/flutter.el#4]
I'm loving this, since I began developing on a 10-year-old ThinkPad with 4Gb of RAM, so having Gradle in the background without having to fire up Android Studio is the only way to go.

However, after exiting Emacs, one has to manually kill Gradle, as it sits there, idling, using a good part of the machine's RAM.

Still, just a very minor quirk.

I'll suggest the Spacemacs community to include `flutter` in the `dart` layer, as both go well together.

**Comment by amake** [comment]
That's the [Gradle daemon](https://docs.gradle.org/current/userguide/gradle_daemon.html). There are lots of ways to configure it, including disabling it entirely. I don't think it makes sense to include any such functionality in flutter.el.
