### ISSUE TITLE
can autocompleter?

### ISSUE THREAD

**Issue by dmlzj** [amake/flutter.el#5]
I hope it can autocompleter.

**Comment by amake** [comment]
I assume you are talking about autocompletion for writing Dart code. That is only tangentially related to this project.

You can get autocompletion for `dart-mode` with [company-lsp](https://github.com/tigersoldier/company-lsp). See [my config](https://github.com/amake/.emacs.d/blob/32886d9266016db13be847f859885836d8357428/init.el#L807), particularly the sections for `company`, `lsp-mode`, `company-lsp`, and `dart-mode`.
